import {
  ADMIN_MODULES,
  ALL_PERMISSIONS,
  PERMISSION_DESCRIPTIONS,
  ROLE_LABELS,
  ROLES,
  STAFF_ROLES,
} from "./constants";
import { DEFAULT_ROLE_PERMISSIONS } from "./matrix";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;

function describe(permission: string): string {
  const special = PERMISSION_DESCRIPTIONS[permission as keyof typeof PERMISSION_DESCRIPTIONS];
  if (special) return special;
  const [module, action] = permission.split(".");
  return `${action === "write" ? "Create, edit and delete" : "View"} ${module}`;
}

function moduleOf(permission: string): string {
  const [prefix] = permission.split(".");
  return (ADMIN_MODULES as readonly string[]).includes(prefix) ? prefix : "system";
}

/**
 * Renders the idempotent RBAC seed migration from the TypeScript matrix.
 * Run `pnpm rbac:generate` after editing constants.ts or matrix.ts.
 */
export function renderRbacSeedSql(): string {
  const roles = ROLES.map(
    (r) => `  (${q(r)}, ${q(ROLE_LABELS[r])}, ${STAFF_ROLES.includes(r) ? "true" : "false"})`,
  ).join(",\n");
  const perms = ALL_PERMISSIONS.map((p) => `  (${q(p)}, ${q(moduleOf(p))}, ${q(describe(p))})`).join(",\n");
  const grants = ROLES.flatMap((r) => DEFAULT_ROLE_PERMISSIONS[r].map((p) => `  (${q(r)}, ${q(p)})`)).join(
    ",\n",
  );

  return `-- GENERATED by \`pnpm rbac:generate\` from lib/permissions/*.ts. Do not edit by hand.
-- Idempotent: safe to re-run. Later matrix changes ship as a new generated migration.

insert into public.roles (key, name, is_staff) values
${roles}
on conflict (key) do update set name = excluded.name, is_staff = excluded.is_staff;

insert into public.permissions (key, module, description) values
${perms}
on conflict (key) do update set module = excluded.module, description = excluded.description;

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
from (values
${grants}
) as g(role_key, permission_key)
join public.roles r on r.key = g.role_key
join public.permissions p on p.key = g.permission_key
on conflict do nothing;
`;
}
