import {
  Accessibility,
  ArrowUpDown,
  BatteryCharging,
  Bike,
  Building2,
  Bus,
  Camera,
  Car,
  CarTaxiFront,
  Cctv,
  Clapperboard,
  Clock,
  Compass,
  ConciergeBell,
  Headset,
  Heart,
  House,
  Leaf,
  MapPin,
  Megaphone,
  MonitorCog,
  Pill,
  Plane,
  Share2,
  ShieldCheck,
  Shirt,
  ShoppingCart,
  ShowerHead,
  Snowflake,
  Sparkles,
  SquareParking,
  TrendingUp,
  Tv,
  UserRound,
  Users,
  Utensils,
  UtensilsCrossed,
  Wifi,
  type LucideIcon,
} from "lucide-react";

/**
 * Icons the admin can pick for services and CMS items, by lucide name.
 * Kept to an explicit list so the client bundle doesn't ship all of lucide.
 */
export const ICONS: Record<string, LucideIcon> = {
  accessibility: Accessibility,
  "arrow-up-down": ArrowUpDown,
  "battery-charging": BatteryCharging,
  bike: Bike,
  "building-2": Building2,
  bus: Bus,
  camera: Camera,
  "car-taxi-front": CarTaxiFront,
  car: Car,
  cctv: Cctv,
  clapperboard: Clapperboard,
  clock: Clock,
  compass: Compass,
  "concierge-bell": ConciergeBell,
  headset: Headset,
  heart: Heart,
  house: House,
  leaf: Leaf,
  "map-pin": MapPin,
  megaphone: Megaphone,
  "monitor-cog": MonitorCog,
  pill: Pill,
  plane: Plane,
  "share-2": Share2,
  "shield-check": ShieldCheck,
  shirt: Shirt,
  "shopping-cart": ShoppingCart,
  "shower-head": ShowerHead,
  snowflake: Snowflake,
  sparkles: Sparkles,
  "square-parking": SquareParking,
  "trending-up": TrendingUp,
  tv: Tv,
  "user-round": UserRound,
  users: Users,
  "utensils-crossed": UtensilsCrossed,
  utensils: Utensils,
  wifi: Wifi,
};

export const ICON_NAMES = Object.keys(ICONS).sort();

export function getIcon(name: string | null | undefined): LucideIcon {
  return (name && ICONS[name]) || Sparkles;
}
